###
POST http://localhost:8080/api/tasks/create
Content-Type: application/json

{
  "userId": 1,
  "title": "Task 2",
  "description": "Task 2 description",
  "priority": "LOW",
  "dueDate": 1,
  "completed": false
}

###
# User
###
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "username": "user",
  "email": "strike0109k@gmail.com",
  "password": "Password@123"
}